# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"\xb0\x01\n\x15\x46raudDetectionRequest\x12\'\n\x04user\x18\x01 \x01(\x0b\x32\x19.fraud_detection.UserInfo\x12\x34\n\x0b\x63redit_card\x18\x02 \x01(\x0b\x32\x1f.fraud_detection.CreditCardInfo\x12\x38\n\x0f\x62illing_address\x18\x03 \x01(\x0b\x32\x1f.fraud_detection.BillingAddress\")\n\x08UserInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"K\n\x0e\x43reditCardInfo\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"?\n\x16\x46raudDetectionResponse\x12\x15\n\ris_fraudulent\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2p\n\x0e\x46raudDetection\x12^\n\x0b\x44\x65tectFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=43
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=219
  _globals['_USERINFO']._serialized_start=221
  _globals['_USERINFO']._serialized_end=262
  _globals['_CREDITCARDINFO']._serialized_start=264
  _globals['_CREDITCARDINFO']._serialized_end=339
  _globals['_BILLINGADDRESS']._serialized_start=341
  _globals['_BILLINGADDRESS']._serialized_end=432
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=434
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=497
  _globals['_FRAUDDETECTION']._serialized_start=499
  _globals['_FRAUDDETECTION']._serialized_end=611
# @@protoc_insertion_point(module_scope)
