# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\xac\x02\n\x18VerifyTransactionRequest\x12\x30\n\x04user\x18\x01 \x01(\x0b\x32\".transaction_verification.UserInfo\x12=\n\x0b\x63redit_card\x18\x02 \x01(\x0b\x32(.transaction_verification.CreditCardInfo\x12\x41\n\x0f\x62illing_address\x18\x03 \x01(\x0b\x32(.transaction_verification.BillingAddress\x12-\n\x05items\x18\x04 \x03(\x0b\x32\x1e.transaction_verification.Item\x12\x15\n\rgift_wrapping\x18\x05 \x01(\x08\x12\x16\n\x0eterms_accepted\x18\x06 \x01(\x08\")\n\x08UserInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"K\n\x0e\x43reditCardInfo\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"0\n\x19VerifyTransactionResponse\x12\x13\n\x0bis_verified\x18\x01 \x01(\x08\x32\x97\x01\n\x17TransactionVerification\x12|\n\x11VerifyTransaction\x12\x32.transaction_verification.VerifyTransactionRequest\x1a\x33.transaction_verification.VerifyTransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYTRANSACTIONREQUEST']._serialized_start=61
  _globals['_VERIFYTRANSACTIONREQUEST']._serialized_end=361
  _globals['_USERINFO']._serialized_start=363
  _globals['_USERINFO']._serialized_end=404
  _globals['_CREDITCARDINFO']._serialized_start=406
  _globals['_CREDITCARDINFO']._serialized_end=481
  _globals['_BILLINGADDRESS']._serialized_start=483
  _globals['_BILLINGADDRESS']._serialized_end=574
  _globals['_ITEM']._serialized_start=576
  _globals['_ITEM']._serialized_end=614
  _globals['_VERIFYTRANSACTIONRESPONSE']._serialized_start=616
  _globals['_VERIFYTRANSACTIONRESPONSE']._serialized_end=664
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=667
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=818
# @@protoc_insertion_point(module_scope)
